# Generated by Django 4.1.3 on 2022-11-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='user', default='noname', max_length=25)),
                ('customer_name', models.CharField(db_column='customer_name', default='noname', max_length=25)),
                ('address', models.CharField(db_column='address', default='nonexistent', max_length=100)),
                ('phone_number', models.CharField(db_column='phone_number', default='0000000000', max_length=15)),
                ('total_price', models.IntegerField(db_column='total_price', default=0)),
                ('status', models.CharField(db_column='status', default='Pending', max_length=10)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=25)),
                ('product_image', models.CharField(blank=True, db_column='product_image', max_length=100)),
                ('company', models.CharField(max_length=25)),
                ('product_description', models.TextField(db_column='product_description')),
                ('quantity_in_stock', models.IntegerField(db_column='quantity_in_stock')),
                ('sell_price', models.IntegerField(db_column='sell_price')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ord', models.AutoField(db_column='ord', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='products.orders')),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'orderdetails',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
