# Generated by Django 4.1.3 on 2022-11-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ord', models.AutoField(db_column='ord', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('user', models.CharField(db_column='user', max_length=25)),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
